location / {
	root /opt/cyops-api;
        try_files /maint.html /503.html @siteup;
}
location @siteup {
        root /opt/cyops-api/public;
        index index.php;
        try_files $uri @rewriteapp;
}
location @rewriteapp {
rewrite ^(.*)$ /index.php/$1 last;
}
location ~ /\.ht {
deny all;
}