user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    map $request_uri $log_args {
        default          $request_uri;
        ~^(.*)secretKey=[^&]*(.*)$ $1secretKey=*****$2;
    }

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request_method $log_args" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
    underscores_in_headers on;

    autoindex off;

    #
    # Limiting the size of the request body helps prevent unexpectedly long or large client requests from being passed \
    # to an application to perform buffer overflow attacks. This value should be set low enough to protect the application \
    # but high enough not to interfere with functionality and block legitimate request bodies.
    #
    client_max_body_size 100K;

    # Setting the send_timeout directive on the server side helps mitigate slow HTTP denial of service attacks \
    # by ensuring write operations taking up large amounts of time are closed.
    #
    send_timeout 10;

    #
    # Attackers can conduct reconnaissance on a website using these response headers, then target attacks for specific \
    # known vulnerabilities associated with the underlying technologies. Hiding the version will slow down and deter some potential attackers.
    #
    server_tokens off;

    #
    # OCSP stapling protects your users from accessing a website where a private key is believed to be compromised. \
    # If a private key is compromised, an attacker may be able to obtain unauthorized access to the encrypted data transmitted by a user.
    #
    ssl_stapling on;
    ssl_stapling_verify on;

    #
    # Setting the client header and body timeouts help your server mitigate possible denial of service attacks. \
    # By timing out a request, the server is able to free up resources that may be waiting for the body or header.
    #
    client_body_timeout 10;
    client_header_timeout 10;

    #
    # Implementing the X-Content-Type-Options header with the "nosniff" directive helps to prevent \
    # drive-by download attacks where a user agent is sniffing content types in responses.
    #
    add_header X-Content-Type-Options "nosniff";

    #
    # The large_client_header_buffers directive may assist in preventing buffer overflow \
    # attacks that leverage long URI query parameters.
    #
    large_client_header_buffers 4 8k;

    #
    # X-Xss-Protection allows you to protect users whose browsers do not support Content Security Policy (generally older browsers), \
    # or protect users if you do not have a Content Security Policy.
    #
    add_header X-Xss-Protection "1; mode=block";
}
