server {
    listen 127.0.0.1:9595 ssl;
    server_name localhost;
    charset     utf-8;

    # max upload size
    client_max_body_size 512M;

    # Django static
    location /integration/static {
        alias /opt/cyops-integrations/web/static;
    }

    # Finally, send all non-media requests to the Django server.
    location / {
        uwsgi_pass  unix:/var/run/uwsgi-integrations/integrations.socket;
        include     /opt/cyops-integrations/integrations/integrations/uwsgi_params;
        uwsgi_read_timeout  1800;
    }
    error_log /var/log/cyops/cyops-integrations/ssl_cyops_integrations_error.log;
    access_log /var/log/cyops/cyops-integrations/ssl_cyops_integrations_access.log main;

    # read more here http://tautt.com/best-nginx-configuration-for-security/
    server_tokens off;
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";

    ssl_dhparam /etc/nginx/ssl/dh4096.pem;

    ssl_prefer_server_ciphers on;
    ssl_protocols TLSv1.3;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";

    ssl_certificate /etc/nginx/ssl/server.leaf.crt;
    ssl_certificate_key /etc/nginx/ssl/server.leaf.key;

    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;
}
