#!/usr/bin/env node
/* Regenerable JS→JSON extractor for the FortiSOAR Jinja filter catalog.
 *
 * The authoritative filter list lives in the Jinja-editor widget as a browser
 * constants module (`ns.filterSignatures`, ~238 entries across string /
 * collection / number / value / encoding / fortisoar / regex / date / set /
 * fortisoarDateFunctions groups). The Python compiler's `unknown_jinja_filter`
 * check needs the same set offline, so we evaluate the widget module against a
 * tiny `window` stub and dump a stable JSON the linter loads.
 *
 * Usage:
 *   node tooling/extract_jinja_filters.js \
 *     [path/to/jinjaFilters.constants.js] [out.json]
 *
 * Defaults match the WebStorm widget repo + this repo's `_data/`. Re-run when
 * the widget catalog changes; the output is checked in so offline CI needs no
 * widget checkout.
 */
"use strict";
const fs = require("fs");
const path = require("path");
const vm = require("vm");

const DEFAULT_SRC =
  "/Users/dylanspille/WebstormProjects/fsr_all_widgets/widgets-src/" +
  "widget-jinja-editor/widget/widgetAssets/js/constants/" +
  "jinjaFilters.constants.js";
const DEFAULT_OUT = path.join(
  __dirname, "..", "fsr_playbooks", "_data", "jinja_filters.json");

const src = process.argv[2] || DEFAULT_SRC;
const out = process.argv[3] || DEFAULT_OUT;

const code = fs.readFileSync(src, "utf8");
const sandbox = { window: {} };
vm.createContext(sandbox);
vm.runInContext(code, sandbox, { filename: src });

const ns = sandbox.window.JinjaEditorWidget || {};
const sigs = ns.filterSignatures || {};
const names = Object.keys(sigs).sort();
if (names.length === 0) {
  console.error("no filterSignatures found in", src);
  process.exit(1);
}

// Keep the linter's payload small + stable: name → {category, params, returns}.
// `params` is the count of declared parameters (used to sanity-check arity if
// we ever want to); `returns` is the declared return type. The membership set
// is just the keys.
const filters = {};
for (const name of names) {
  const e = sigs[name] || {};
  filters[name] = {
    category: e.category || "Other",
    params: Array.isArray(e.parameters) ? e.parameters.length : 0,
    returns: (e.returnValue && e.returnValue.type) || "any",
  };
}

const payload = {
  _comment:
    "FortiSOAR Jinja filter catalog. Generated by " +
    "tooling/extract_jinja_filters.js from the widget's " +
    "jinjaFilters.constants.js. Do not hand-edit; re-run the extractor.",
  count: names.length,
  filters,
};
fs.writeFileSync(out, JSON.stringify(payload, null, 2) + "\n");
console.error(`wrote ${names.length} filters → ${out}`);
