"""Agent-facing assets: the externalized system prompt + helpers.

Kept inside the `python/` tree (not `web/`) so non-web frontends —
CLI agents, the eval harness, the MCP-driven Claude Code session —
can load the SAME prompt without depending on the web backend.
"""
from __future__ import annotations

from pathlib import Path

_PROMPT_PATH = Path(__file__).with_name("system_prompt.md")
_STATIC_BLOCK_PATH = Path(__file__).with_name("static_grammar_block.md")


def load_system_prompt() -> str:
    """Return the externalized FSR-authoring system prompt as text.

    If `static_grammar_block.md` is present alongside, prepend it.
    That block holds byte-identical-across-tenants reference content
    (step shapes, FSR-custom Jinja symbols, grammar rules) so
    Anthropic prompt caching can amortize it across turns. The block
    is generated by `scripts/build_static_prompt.py`; re-run when the
    reference store refreshes.

    Callers MUST NOT inline this content — pull it through this
    helper so the cached prefix stays byte-stable.
    """
    parts: list[str] = []
    if _STATIC_BLOCK_PATH.exists():
        parts.append(_STATIC_BLOCK_PATH.read_text(encoding="utf-8"))
        parts.append("\n---\n")
    parts.append(_PROMPT_PATH.read_text(encoding="utf-8"))
    return "".join(parts)


__all__ = ["load_system_prompt"]
